### ISSUE TITLE
ImportError: cannot import name discovery

### ISSUE THREAD

**Issue by von-forks** [deltaray/cloudperm#1]
What version of apiclient are you using? With 1.0.2 I'm seeing the following. I also had to install urllib3 to get to this point.

```
% listFiles.py
Traceback (most recent call last):
  File "/usr/local/bin/listFiles.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/vwelch/develop/gdoc_perm_checker/listFiles.py", line 11, in <module>
    from apiclient import discovery
ImportError: cannot import name discovery

```

**Comment by deltaray** [comment]
According to `print apiclient.__version__` I'm using 1.4.2

**Comment by von** [comment]
Ah, I think you are using https://pypi.python.org/pypi/google-api-python-client/ ?
As opposed to https://pypi.python.org/pypi/apiclient/1.0.2

**Comment by deltaray** [comment]
Thanks. I fixed this documentation issue.
